<a href="https://colab.research.google.com/github/divx1979/Kaggle-Projects/blob/master/Kaggle_Fake_News_Class_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Develop a machine learning program to identify when an article might be fake news

In [1]:
import pandas as pd

In [2]:
## data taken from 
## https://www.kaggle.com/competitions/fake-news/data

In [81]:
import numpy as np
import matplotlib.pyplot as plt

In [13]:
data1 = pd.read_csv('/content/train.csv')

In [5]:
data_test = pd.read_csv('/content/test.csv')

In [8]:
data_test.shape

(5200, 4)

In [9]:
## For this project, I'll be just using the test file as the train .csv is too large and hence,
## takes a long time to load up

In [10]:
# data_test.head()

,id,title,author,text
0,20800,"Specter of Trump Loosens Tongues, if Not Purse...",David Streitfeld,"PALO ALTO, Calif. — After years of scorning..."
1,20801,Russian warships ready to strike terrorists ne...,NaN,Russian warships ready to strike terrorists ne...
2,20802,#NoDAPL: Native American Leaders Vow to Stay A...,Common Dreams,Videos #NoDAPL: Native American Leaders Vow to...
3,20803,"Tim Tebow Will Attempt Another Comeback, This ...",Daniel Victor,"If at first you don’t succeed, try a different..."
4,20804,Keiser Report: Meme Wars (E995),Truth Broadcast Network,42 mins ago 1 Views 0 Comments 0 Likes 'For th...

In [14]:
## So now I'll just drop the 'label'(i.e. dependent feature) in order to create X, y

X = data1.drop('label', axis = 1)

In [15]:
y = data1['label']

In [16]:
X.head()

,id,title,author,text
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ..."
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...

In [17]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

In [18]:
data1.shape

(20800, 5)

In [19]:
## Now, let's import the TF IDF Vec
from sklearn.feature_extraction.text import TfidfVectorizer

In [40]:
df1 = data1.dropna()

In [41]:
df1.head(20)

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1
5,5,Jackie Mason: Hollywood Would Love Trump if He...,Daniel Nussbaum,"In these trying times, Jackie Mason is the Voi...",0
7,7,Benoît Hamon Wins French Socialist Party’s Pre...,Alissa J. Rubin,"PARIS — France chose an idealistic, traditi...",0
9,9,"A Back-Channel Plan for Ukraine and Russia, Co...",Megan Twohey and Scott Shane,A week before Michael T. Flynn resigned as nat...,0
10,10,Obama’s Organizing for Action Partners with So...,Aaron Klein,"Organizing for Action, the activist group that...",0
11,11,"BBC Comedy Sketch ""Real Housewives of ISIS"" Ca...",Chris Tomlinson,The BBC produced spoof on the “Real Housewives...,0
12,12,Russian Researchers Discover Secret Nazi Milit...,Amando Flavio,The mystery surrounding The Third Reich and Na...,1
13,13,US Officials See No Link Between Trump and Russia,Jason Ditz,Clinton Campaign Demands FBI Affirm Trump's Ru...,1
14,14,"Re: Yes, There Are Paid Government Trolls On S...",AnotherAnnie,"Yes, There Are Paid Government Trolls On Socia...",1
15,15,"In Major League Soccer, Argentines Find a Home...",Jack Williams,Guillermo Barros Schelotto was not the first A...,0
16,16,Wells Fargo Chief Abruptly Steps Down - The Ne...,Michael Corkery and Stacy Cowley,The scandal engulfing Wells Fargo toppled its ...,0
17,17,Anonymous Donor Pays $2.5 Million To Release E...,Starkman,A Caddo Nation tribal leader has just been fre...,1
18,18,FBI Closes In On Hillary!,The Doc,FBI Closes In On Hillary! Posted on Home » Hea...,1
19,19,Chuck Todd: ’BuzzFeed Did Donald Trump a Polit...,Jeff Poor,Wednesday after Donald Trump’s press confere...,0
21,21,"Monica Lewinsky, Clinton Sex Scandal Set for ’...",Jerome Hudson,"Screenwriter Ryan Murphy, who has produced the...",0
22,22,Rob Reiner: Trump Is ’Mentally Unstable’ - Bre...,Pam Key,"Sunday on MSNBC’s “AM Joy,” actor and director...",0

In [42]:
## we need to now reset the index val so we can run feature eng

df1.reset_index(inplace = True)

In [65]:
df1.head(20)

,index,id,title,author,text,label
0,0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1
5,5,5,Jackie Mason: Hollywood Would Love Trump if He...,Daniel Nussbaum,"In these trying times, Jackie Mason is the Voi...",0
6,7,7,Benoît Hamon Wins French Socialist Party’s Pre...,Alissa J. Rubin,"PARIS — France chose an idealistic, traditi...",0
7,9,9,"A Back-Channel Plan for Ukraine and Russia, Co...",Megan Twohey and Scott Shane,A week before Michael T. Flynn resigned as nat...,0
8,10,10,Obama’s Organizing for Action Partners with So...,Aaron Klein,"Organizing for Action, the activist group that...",0
9,11,11,"BBC Comedy Sketch ""Real Housewives of ISIS"" Ca...",Chris Tomlinson,The BBC produced spoof on the “Real Housewives...,0
10,12,12,Russian Researchers Discover Secret Nazi Milit...,Amando Flavio,The mystery surrounding The Third Reich and Na...,1
11,13,13,US Officials See No Link Between Trump and Russia,Jason Ditz,Clinton Campaign Demands FBI Affirm Trump's Ru...,1
12,14,14,"Re: Yes, There Are Paid Government Trolls On S...",AnotherAnnie,"Yes, There Are Paid Government Trolls On Socia...",1
13,15,15,"In Major League Soccer, Argentines Find a Home...",Jack Williams,Guillermo Barros Schelotto was not the first A...,0
14,16,16,Wells Fargo Chief Abruptly Steps Down - The Ne...,Michael Corkery and Stacy Cowley,The scandal engulfing Wells Fargo toppled its ...,0
15,17,17,Anonymous Donor Pays $2.5 Million To Release E...,Starkman,A Caddo Nation tribal leader has just been fre...,1
16,18,18,FBI Closes In On Hillary!,The Doc,FBI Closes In On Hillary! Posted on Home » Hea...,1
17,19,19,Chuck Todd: ’BuzzFeed Did Donald Trump a Polit...,Jeff Poor,Wednesday after Donald Trump’s press confere...,0
18,21,21,"Monica Lewinsky, Clinton Sex Scandal Set for ’...",Jerome Hudson,"Screenwriter Ryan Murphy, who has produced the...",0
19,22,22,Rob Reiner: Trump Is ’Mentally Unstable’ - Bre...,Pam Key,"Sunday on MSNBC’s “AM Joy,” actor and director...",0

In [60]:
# msg = df1.copy()

In [61]:
# msg.head()

,index,id,title,author,text,label
0,0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1

In [35]:

# Setup
!pip install -q wordcloud
import wordcloud

import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger') 

import pandas as pd
import matplotlib.pyplot as plt
import io
import unicodedata
import numpy as np
import re
import string

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

In [66]:
## import the lib : stemming, stopwords
## we ar not doing lemmatization as it takes time as the data is too big

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re
ps1 = PorterStemmer()

corpus = []

In [67]:
## feature eng

for i in range(0, len(df1)):
  rev1 = re.sub('[^a-zA-z]', ' ', df1['title'][i])
  rev1 = rev1.lower()
  rev1 = rev1.split()

  rev1 = [ps1.stem(word) for word in rev1 if not word in stopwords.words('english')]
  rev1 = ' '.join(rev1)
  corpus.append(rev1)

In [63]:
# for i in range(0, len(msg)):
#     review = re.sub('[^a-zA-Z]', ' ', msg['title'][i])
#     review = review.lower()
#     review = review.split()
    
#     review = [ps1.stem(word) for word in review if not word in stopwords.words('english')]
#     review = ' '.join(review)
#     corpus.append(review)

In [71]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [70]:
## Applying Tfidf

tfv = TfidfVectorizer(max_features=5000, ngram_range = (1, 3))

X = tfv.fit_transform(corpus).toarray()

In [72]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [73]:
y = msg['label']

In [74]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [75]:
tfv.get_feature_names()[:20]

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['abandon',
 'abc',
 'abc news',
 'abduct',
 'abe',
 'abedin',
 'abl',
 'abort',
 'abroad',
 'absolut',
 'abstain',
 'absurd',
 'abus',
 'abus new',
 'abus new york',
 'academi',
 'accept',
 'access',
 'access pipelin',
 'access pipelin protest']

In [77]:
tfv.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.float64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': 5000,
 'min_df': 1,
 'ngram_range': (1, 3),
 'norm': 'l2',
 'preprocessor': None,
 'smooth_idf': True,
 'stop_words': None,
 'strip_accents': None,
 'sublinear_tf': False,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'use_idf': True,
 'vocabulary': None}

In [78]:
count_df1 = pd.DataFrame(X_train, columns = tfv.get_feature_names())

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [79]:
count_df1.head()

,abandon,abc,abc news,abduct,abe,abedin,abl,abort,abroad,absolut,...,zero,zika,zika viru,zionist,zone,zone new,zone new york,zoo,zu,zuckerberg
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [80]:
## imoprt Naive Bayes

from sklearn.naive_bayes import MultinomialNB
cl = MultinomialNB()

In [82]:
from sklearn import metrics
import itertools

In [88]:
from sklearn.metrics._plot.confusion_matrix import plot_confusion_matrix
cl.fit(X_train, y_train)
pred = cl.predict(X_test)
ac = metrics.accuracy_score(y_test, pred)

cm = metrics.confusion_matrix(y_test, pred)

In [89]:
ac

0.8881596937380366

In [90]:
cm

array([[1925,  115],
       [ 294, 1323]])